# Generated by Django 5.0.2 on 2024-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='film_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
