# Generated by Django 5.0.2 on 2024-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0006_movie_time1_movie_time2_movie_time3_movie_time4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='time1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time4',
            field=models.CharField(max_length=50),
        ),
    ]
