# Generated by Django 5.0.2 on 2024-04-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0007_alter_movie_time1_alter_movie_time2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time4',
        ),
    ]
