# Generated by Django 5.0.2 on 2024-04-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0009_movie_time1_movie_time2_movie_time3_movie_time4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
