# Generated by Django 5.0.2 on 2024-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAccount', '0011_alter_movie_time1_alter_movie_time2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
